# Header
menu:
  主页: /
  存档: /archives
  作品集: /works
  关于我: /about
rss: /atom.xml

# Content
excerpt_link: 继续阅读
fancybox: true

# Sidebar
sidebar: right
widgets:
- category
- tag
- tagcloud
- archive
- recent_posts
- weibo
- adsense
- link

# Miscellaneous
host_name: kuangqi.me
google_analytics: UA-49728497-1
baidu_analytics: true
favicon: /favicon.png
twitter: kuangqi
google_plus:
