# Header
menu:
  主页: /
  存档: /archives
  作品集: /works
  关于我: /about
  《Arduino魔法书》专题页面: /arduino
  本博客源代码: https://gitcafe.com/kqkq/blog
  Fork this blog on GitHub: https://github.com/kqkq/blog
rss: /atom.xml

# Content
excerpt_link: 继续阅读
fancybox: true

# Sidebar
sidebar: right
widgets:
- category
- recent_posts
- tag
- tagcloud
- weibo
- link
# - archive

# Miscellaneous
host_name: kuangqi.me
google_analytics: UA-49728497-1
baidu_analytics: true
switch_banner: true
banner_count: 6
favicon: /favicon.png
twitter: kuangqi
google_plus:
fb_admins:
fb_app_id:
